{
  "openapi": "3.0.3",
  "info": {
    "title": "RESTful API for Fuzzing",
    "version": "1.0",
    "description": "OpenAPI spec for Experimental RESTful API for Fuzzing",
    "contact": {
      "name": "Danar Gumilang Putera",
      "email": "danar.g.putera@gmail.com",
      "url": "https://github.com/bungdanar"
    },
    "license": {
      "name": "MIT",
      "url": "https://opensource.org/license/mit/"
    }
  },
  "servers": [
    {
      "url": "http://localhost:5000/api",
      "description": "Experimental RESTful API Server for Fuzzing"
    }
  ],
  "externalDocs": {
    "url": "https://github.com/bungdanar",
    "description": "Experimental RESTful API Server Written in NodeJs and Python"
  },
  "paths": {
    "/product": {
      "post": {
        "tags": [
          "Product"
        ],
        "summary": "Create a new product",
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/ProductCreatePayload"
              },
              "examples": {
                "CorrectProductCreatePayload": {
                  "$ref": "#/components/examples/CorrectProductCreatePayload"
                },
                "IncorrectProductCreatePayload": {
                  "$ref": "#/components/examples/IncorrectProductCreatePayload"
                }
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Successfully create new product",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ProductResponse"
                }
              }
            }
          },
          "400": {
            "description": "Bad request error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrResponse"
                }
              }
            }
          },
          "500": {
            "description": "Internal server error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrResponse"
                }
              }
            }
          }
        }
      }
    },
    "/product-tag-category": {
      "post": {
        "tags": [
          "Product Tags Category"
        ],
        "summary": "Create a new product with its tags and category",
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/ProductTagCategoryCreatePayload"
              },
              "examples": {
                "CorrectProductTagCategoryCreatePayload": {
                  "$ref": "#/components/examples/CorrectProductTagCategoryCreatePayload"
                },
                "IncorrectProductTagCategoryCreatePayload": {
                  "$ref": "#/components/examples/IncorrectProductTagCategoryCreatePayload"
                }
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Successfully create a new product with its tags and category",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ProductTagCategoryResponse"
                }
              }
            }
          },
          "400": {
            "description": "Bad request error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrResponse"
                }
              }
            }
          },
          "500": {
            "description": "Internal server error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrResponse"
                }
              }
            }
          }
        }
      }
    },
    "/product-tag-category-coupon": {
      "post": {
        "tags": [
          "Product Tags Categories Coupons"
        ],
        "summary": "Create a new product with its tags, categories, and coupons",
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/ProductTagCategoryCouponCreatePayload"
              },
              "examples": {
                "CorrectProductTagCategoryCouponCreatePayload": {
                  "$ref": "#/components/examples/CorrectProductTagCategoryCouponCreatePayload"
                },
                "IncorrectProductTagCategoryCouponCreatePayload": {
                  "$ref": "#/components/examples/IncorrectProductTagCategoryCouponCreatePayload"
                }
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Successfully create a new product with its tags, categories, and coupons",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ProductTagCategoryCouponResponse"
                }
              }
            }
          },
          "400": {
            "description": "Bad request error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrResponse"
                }
              }
            }
          },
          "500": {
            "description": "Internal server error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrResponse"
                }
              }
            }
          }
        }
      }
    },
    "/user": {
      "post": {
        "tags": [
          "User"
        ],
        "summary": "Create a new user",
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/UserCreatePayload"
              },
              "examples": {
                "CorrectUserCreatePayload": {
                  "$ref": "#/components/examples/CorrectUserCreatePayload"
                },
                "IncorrectUserCreatePayload": {
                  "$ref": "#/components/examples/IncorrectUserCreatePayload"
                }
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Successfully create new user",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/UserResponse"
                }
              }
            }
          },
          "400": {
            "description": "Bad request error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrResponse"
                }
              }
            }
          },
          "500": {
            "description": "Internal server error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrResponse"
                }
              }
            }
          }
        }
      }
    },
    "/user-address": {
      "post": {
        "tags": [
          "User Address"
        ],
        "summary": "Create a new user with its address",
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/UserAddressCreatePayload"
              },
              "examples": {
                "CorrectUserAddressCreatePayload": {
                  "$ref": "#/components/examples/CorrectUserAddressCreatePayload"
                },
                "IncorrectUserAddressCreatePayload": {
                  "$ref": "#/components/examples/IncorrectUserAddressCreatePayload"
                }
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Successfully create new user with its address",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/UserAddressResponse"
                }
              }
            }
          },
          "400": {
            "description": "Bad request error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrResponse"
                }
              }
            }
          },
          "500": {
            "description": "Internal server error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrResponse"
                }
              }
            }
          }
        }
      }
    },
    "/user-address-product": {
      "post": {
        "tags": [
          "User Address Product"
        ],
        "summary": "Create a new user with its addresses and product",
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/UserAddressProductCreatePayload"
              },
              "examples": {
                "CorrectUserAddressProductCreatePayload": {
                  "$ref": "#/components/examples/CorrectUserAddressProductCreatePayload"
                },
                "IncorrectUserAddressProductCreatePayload": {
                  "$ref": "#/components/examples/IncorrectUserAddressProductCreatePayload"
                }
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Successfully create new user with its addresses and product",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/UserAddressProductResponse"
                }
              }
            }
          },
          "400": {
            "description": "Bad request error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrResponse"
                }
              }
            }
          },
          "500": {
            "description": "Internal server error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrResponse"
                }
              }
            }
          }
        }
      }
    },
    "/user-address-product-shipping": {
      "post": {
        "tags": [
          "User Address Product Shipping"
        ],
        "summary": "Create a new user with its addresses and product (with its shipping)",
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/UserAddressProductShippingCreatePayload"
              },
              "examples": {
                "CorrectUserAddressProductShippingCreatePayload": {
                  "$ref": "#/components/examples/CorrectUserAddressProductShippingCreatePayload"
                },
                "IncorrectUserAddressProductShippingCreatePayload": {
                  "$ref": "#/components/examples/IncorrectUserAddressProductShippingCreatePayload"
                }
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Successfully create new user with its addresses and product (with its shipping)",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/UserAddressProductShippingResponse"
                }
              }
            }
          },
          "400": {
            "description": "Bad request error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrResponse"
                }
              }
            }
          },
          "500": {
            "description": "Internal server error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrResponse"
                }
              }
            }
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "ProductCreatePayload": {
        "type": "object",
        "required": [
          "name",
          "sku",
          "regular_price",
          "discount_price",
          "quantity",
          "description",
          "weight",
          "note"
        ],
        "properties": {
          "name": {
            "type": "string",
            "minLength": 3,
            "maxLength": 255
          },
          "sku": {
            "type": "string",
            "minLength": 3,
            "maxLength": 255
          },
          "regular_price": {
            "type": "number",
            "format": "float",
            "minimum": 0
          },
          "discount_price": {
            "type": "number",
            "format": "float",
            "minimum": 0,
            "description": "Must be less than or equal to regular_price"
          },
          "quantity": {
            "type": "integer",
            "format": "int32",
            "minimum": 0,
            "maximum": 9999
          },
          "description": {
            "type": "string",
            "minLength": 3,
            "maxLength": 1000
          },
          "weight": {
            "type": "number",
            "format": "float",
            "minimum": 0,
            "maximum": 1000
          },
          "note": {
            "type": "string",
            "minLength": 3,
            "maxLength": 255
          },
          "published": {
            "type": "boolean",
            "default": false
          }
        }
      },
      "TagsCreatePayload": {
        "type": "array",
        "items": {
          "type": "string",
          "minLength": 3,
          "maxLength": 255
        }
      },
      "CategoryCreatePayload": {
        "type": "object",
        "required": [
          "name",
          "description"
        ],
        "properties": {
          "name": {
            "type": "string",
            "minLength": 3,
            "maxLength": 255
          },
          "description": {
            "type": "string",
            "minLength": 3,
            "maxLength": 1000
          }
        }
      },
      "CouponCreatePayload": {
        "type": "object",
        "required": [
          "code",
          "description",
          "discount_value",
          "discount_type",
          "max_usage",
          "start_date",
          "end_date"
        ],
        "properties": {
          "code": {
            "type": "string",
            "minLength": 3,
            "maxLength": 255
          },
          "description": {
            "type": "string",
            "minLength": 3,
            "maxLength": 1000
          },
          "discount_value": {
            "type": "number",
            "format": "float",
            "minimum": 0,
            "maximum": 100
          },
          "discount_type": {
            "type": "string",
            "minLength": 3,
            "maxLength": 255
          },
          "times_used": {
            "type": "integer",
            "format": "int32",
            "minimum": 0,
            "default": 0,
            "description": "Must be less than or equal to max_usage"
          },
          "max_usage": {
            "type": "integer",
            "format": "int32",
            "minimum": 0
          },
          "start_date": {
            "type": "string",
            "format": "date-time"
          },
          "end_date": {
            "type": "string",
            "format": "date-time",
            "description": "Must be greater than or equal to start_date"
          }
        }
      },
      "UserCreatePayload": {
        "type": "object",
        "required": [
          "first_name",
          "last_name",
          "email",
          "phone_code",
          "phone_number"
        ],
        "properties": {
          "first_name": {
            "type": "string",
            "minLength": 3,
            "maxLength": 255
          },
          "last_name": {
            "type": "string",
            "minLength": 3,
            "maxLength": 255
          },
          "email": {
            "type": "string",
            "pattern": "^[A-Z0-9._%-]+@[A-Z0-9.-]+.[A-Z]{2,4}$",
            "maxLength": 255
          },
          "phone_code": {
            "type": "string",
            "pattern": "^[0-9]{1,3}$",
            "minLength": 1,
            "maxLength": 3
          },
          "phone_number": {
            "type": "string",
            "pattern": "^[0-9]{4,12}$",
            "minLength": 4,
            "maxLength": 12
          }
        }
      },
      "AddressCreatePayload": {
        "type": "object",
        "required": [
          "street",
          "city",
          "country",
          "postal_code"
        ],
        "properties": {
          "street": {
            "type": "string",
            "minLength": 3,
            "maxLength": 255
          },
          "city": {
            "type": "string",
            "minLength": 3,
            "maxLength": 255
          },
          "country": {
            "type": "string",
            "minLength": 3,
            "maxLength": 255
          },
          "postal_code": {
            "type": "string",
            "pattern": "^[0-9]{5}$",
            "minLength": 5,
            "maxLength": 5
          }
        }
      },
      "ShippingCreatePayload": {
        "type": "object",
        "required": [
          "description",
          "charge",
          "estimated_days"
        ],
        "properties": {
          "description": {
            "type": "string",
            "minLength": 3,
            "maxLength": 1000
          },
          "charge": {
            "type": "number",
            "format": "float",
            "minimum": 0
          },
          "free": {
            "type": "boolean",
            "default": false
          },
          "estimated_days": {
            "type": "integer",
            "format": "int32",
            "minimum": 0,
            "maximum": 8
          }
        }
      },
      "ProductTagCategoryCreatePayload": {
        "type": "object",
        "required": [
          "name",
          "sku",
          "regular_price",
          "discount_price",
          "quantity",
          "description",
          "weight",
          "note",
          "tags",
          "category"
        ],
        "properties": {
          "name": {
            "type": "string",
            "minLength": 3,
            "maxLength": 255
          },
          "sku": {
            "type": "string",
            "minLength": 3,
            "maxLength": 255
          },
          "regular_price": {
            "type": "number",
            "format": "float",
            "minimum": 0
          },
          "discount_price": {
            "type": "number",
            "format": "float",
            "minimum": 0,
            "description": "Must be less than or equal to regular_price"
          },
          "quantity": {
            "type": "integer",
            "format": "int32",
            "minimum": 0,
            "maximum": 9999
          },
          "description": {
            "type": "string",
            "minLength": 3,
            "maxLength": 1000
          },
          "weight": {
            "type": "number",
            "format": "float",
            "minimum": 0,
            "maximum": 1000
          },
          "note": {
            "type": "string",
            "minLength": 3,
            "maxLength": 255
          },
          "published": {
            "type": "boolean",
            "default": false
          },
          "tags": {
            "$ref": "#/components/schemas/TagsCreatePayload"
          },
          "category": {
            "$ref": "#/components/schemas/CategoryCreatePayload"
          }
        }
      },
      "ProductTagCategoryCouponCreatePayload": {
        "type": "object",
        "required": [
          "name",
          "sku",
          "regular_price",
          "discount_price",
          "quantity",
          "description",
          "weight",
          "note",
          "tags",
          "categories",
          "coupons"
        ],
        "properties": {
          "name": {
            "type": "string",
            "minLength": 3,
            "maxLength": 255
          },
          "sku": {
            "type": "string",
            "minLength": 3,
            "maxLength": 255
          },
          "regular_price": {
            "type": "number",
            "format": "float",
            "minimum": 0
          },
          "discount_price": {
            "type": "number",
            "format": "float",
            "minimum": 0,
            "description": "Must be less than or equal to regular_price"
          },
          "quantity": {
            "type": "integer",
            "format": "int32",
            "minimum": 0,
            "maximum": 9999
          },
          "description": {
            "type": "string",
            "minLength": 3,
            "maxLength": 1000
          },
          "weight": {
            "type": "number",
            "format": "float",
            "minimum": 0,
            "maximum": 1000
          },
          "note": {
            "type": "string",
            "minLength": 3,
            "maxLength": 255
          },
          "published": {
            "type": "boolean",
            "default": false
          },
          "tags": {
            "$ref": "#/components/schemas/TagsCreatePayload"
          },
          "categories": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/CategoryCreatePayload"
            }
          },
          "coupons": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/CouponCreatePayload"
            }
          }
        }
      },
      "UserAddressCreatePayload": {
        "type": "object",
        "required": [
          "first_name",
          "last_name",
          "email",
          "phone_code",
          "phone_number",
          "address"
        ],
        "properties": {
          "first_name": {
            "type": "string",
            "minLength": 3,
            "maxLength": 255
          },
          "last_name": {
            "type": "string",
            "minLength": 3,
            "maxLength": 255
          },
          "email": {
            "type": "string",
            "pattern": "^[A-Z0-9._%-]+@[A-Z0-9.-]+.[A-Z]{2,4}$",
            "maxLength": 255
          },
          "phone_code": {
            "type": "string",
            "pattern": "^[0-9]{1,3}$",
            "minLength": 1,
            "maxLength": 3
          },
          "phone_number": {
            "type": "string",
            "pattern": "^[0-9]{4,12}$",
            "minLength": 4,
            "maxLength": 12
          },
          "address": {
            "$ref": "#/components/schemas/AddressCreatePayload"
          }
        }
      },
      "UserAddressProductCreatePayload": {
        "type": "object",
        "required": [
          "first_name",
          "last_name",
          "email",
          "phone_code",
          "phone_number",
          "addresses",
          "product"
        ],
        "properties": {
          "first_name": {
            "type": "string",
            "minLength": 3,
            "maxLength": 255
          },
          "last_name": {
            "type": "string",
            "minLength": 3,
            "maxLength": 255
          },
          "email": {
            "type": "string",
            "pattern": "^[A-Z0-9._%-]+@[A-Z0-9.-]+.[A-Z]{2,4}$",
            "maxLength": 255
          },
          "phone_code": {
            "type": "string",
            "pattern": "^[0-9]{1,3}$",
            "minLength": 1,
            "maxLength": 3
          },
          "phone_number": {
            "type": "string",
            "pattern": "^[0-9]{4,12}$",
            "minLength": 4,
            "maxLength": 12
          },
          "addresses": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/AddressCreatePayload"
            }
          },
          "product": {
            "$ref": "#/components/schemas/ProductCreatePayload"
          }
        }
      },
      "UserAddressProductShippingCreatePayload": {
        "type": "object",
        "required": [
          "first_name",
          "last_name",
          "email",
          "phone_code",
          "phone_number",
          "addresses",
          "product",
          "shipping"
        ],
        "properties": {
          "first_name": {
            "type": "string",
            "minLength": 3,
            "maxLength": 255
          },
          "last_name": {
            "type": "string",
            "minLength": 3,
            "maxLength": 255
          },
          "email": {
            "type": "string",
            "pattern": "^[A-Z0-9._%-]+@[A-Z0-9.-]+.[A-Z]{2,4}$",
            "maxLength": 255
          },
          "phone_code": {
            "type": "string",
            "pattern": "^[0-9]{1,3}$",
            "minLength": 1,
            "maxLength": 3
          },
          "phone_number": {
            "type": "string",
            "pattern": "^[0-9]{4,12}$",
            "minLength": 4,
            "maxLength": 12
          },
          "addresses": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/AddressCreatePayload"
            }
          },
          "product": {
            "$ref": "#/components/schemas/ProductCreatePayload"
          },
          "shipping": {
            "$ref": "#/components/schemas/ShippingCreatePayload"
          }
        }
      },
      "TagResponse": {
        "type": "object",
        "properties": {
          "id": {
            "type": "integer",
            "format": "int32"
          },
          "name": {
            "type": "string"
          },
          "created_at": {
            "type": "string",
            "format": "date-time"
          },
          "updated_at": {
            "type": "string",
            "format": "date-time"
          }
        }
      },
      "CategoryResponse": {
        "type": "object",
        "properties": {
          "id": {
            "type": "integer",
            "format": "int32"
          },
          "name": {
            "type": "string"
          },
          "description": {
            "type": "string"
          },
          "active": {
            "type": "boolean"
          },
          "created_at": {
            "type": "string",
            "format": "date-time"
          },
          "updated_at": {
            "type": "string",
            "format": "date-time"
          }
        }
      },
      "CouponResponse": {
        "type": "object",
        "properties": {
          "id": {
            "type": "integer",
            "format": "int32"
          },
          "code": {
            "type": "string"
          },
          "description": {
            "type": "string"
          },
          "discount_value": {
            "type": "number",
            "format": "float"
          },
          "discount_type": {
            "type": "string"
          },
          "times_used": {
            "type": "integer",
            "format": "int32"
          },
          "max_usage": {
            "type": "integer",
            "format": "int32"
          },
          "start_date": {
            "type": "string",
            "format": "date-time"
          },
          "end_date": {
            "type": "string",
            "format": "date-time"
          },
          "created_at": {
            "type": "string",
            "format": "date-time"
          },
          "updated_at": {
            "type": "string",
            "format": "date-time"
          }
        }
      },
      "ProductResponse": {
        "type": "object",
        "properties": {
          "id": {
            "type": "integer",
            "format": "int32"
          },
          "name": {
            "type": "string"
          },
          "sku": {
            "type": "string"
          },
          "regular_price": {
            "type": "number",
            "format": "float"
          },
          "discount_price": {
            "type": "number",
            "format": "float"
          },
          "quantity": {
            "type": "integer",
            "format": "int32"
          },
          "description": {
            "type": "string"
          },
          "weight": {
            "type": "number",
            "format": "float"
          },
          "note": {
            "type": "string"
          },
          "published": {
            "type": "boolean"
          },
          "seller_id": {
            "type": "integer",
            "format": "int32"
          },
          "created_at": {
            "type": "string",
            "format": "date-time"
          },
          "updated_at": {
            "type": "string",
            "format": "date-time"
          }
        }
      },
      "UserResponse": {
        "type": "object",
        "properties": {
          "id": {
            "type": "integer",
            "format": "int32"
          },
          "first_name": {
            "type": "string"
          },
          "last_name": {
            "type": "string"
          },
          "email": {
            "type": "string",
            "pattern": "^[A-Z0-9._%-]+@[A-Z0-9.-]+.[A-Z]{2,4}$"
          },
          "phone_code": {
            "type": "string",
            "pattern": "^[0-9]{1,3}$"
          },
          "phone_number": {
            "type": "string",
            "pattern": "^[0-9]{4,12}$"
          },
          "created_at": {
            "type": "string",
            "format": "date-time"
          },
          "updated_at": {
            "type": "string",
            "format": "date-time"
          }
        }
      },
      "AddressResponse": {
        "type": "object",
        "properties": {
          "id": {
            "type": "integer",
            "format": "int32"
          },
          "street": {
            "type": "string"
          },
          "city": {
            "type": "string"
          },
          "country": {
            "type": "string"
          },
          "postal_code": {
            "type": "string",
            "pattern": "^[0-9]{5}$"
          },
          "user_id": {
            "type": "integer",
            "format": "int32"
          },
          "created_at": {
            "type": "string",
            "format": "date-time"
          },
          "updated_at": {
            "type": "string",
            "format": "date-time"
          }
        }
      },
      "ShippingResponse": {
        "type": "object",
        "properties": {
          "id": {
            "type": "integer",
            "format": "int32"
          },
          "description": {
            "type": "string"
          },
          "charge": {
            "type": "number",
            "format": "float"
          },
          "free": {
            "type": "boolean"
          },
          "estimated_days": {
            "type": "integer",
            "format": "int32"
          },
          "product_id": {
            "type": "integer",
            "format": "int32"
          },
          "created_at": {
            "type": "string",
            "format": "date-time"
          },
          "updated_at": {
            "type": "string",
            "format": "date-time"
          }
        }
      },
      "ProductTagCategoryResponse": {
        "type": "object",
        "properties": {
          "id": {
            "type": "integer",
            "format": "int32"
          },
          "name": {
            "type": "string"
          },
          "sku": {
            "type": "string"
          },
          "regular_price": {
            "type": "number",
            "format": "float"
          },
          "discount_price": {
            "type": "number",
            "format": "float"
          },
          "quantity": {
            "type": "integer",
            "format": "int32"
          },
          "description": {
            "type": "string"
          },
          "weight": {
            "type": "number",
            "format": "float"
          },
          "note": {
            "type": "string"
          },
          "published": {
            "type": "boolean"
          },
          "seller_id": {
            "type": "integer",
            "format": "int32"
          },
          "created_at": {
            "type": "string",
            "format": "date-time"
          },
          "updated_at": {
            "type": "string",
            "format": "date-time"
          },
          "tags": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/TagResponse"
            }
          },
          "categories": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/CategoryResponse"
            }
          }
        }
      },
      "ProductTagCategoryCouponResponse": {
        "type": "object",
        "properties": {
          "id": {
            "type": "integer",
            "format": "int32"
          },
          "name": {
            "type": "string"
          },
          "sku": {
            "type": "string"
          },
          "regular_price": {
            "type": "number",
            "format": "float"
          },
          "discount_price": {
            "type": "number",
            "format": "float"
          },
          "quantity": {
            "type": "integer",
            "format": "int32"
          },
          "description": {
            "type": "string"
          },
          "weight": {
            "type": "number",
            "format": "float"
          },
          "note": {
            "type": "string"
          },
          "published": {
            "type": "boolean"
          },
          "seller_id": {
            "type": "integer",
            "format": "int32"
          },
          "created_at": {
            "type": "string",
            "format": "date-time"
          },
          "updated_at": {
            "type": "string",
            "format": "date-time"
          },
          "tags": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/TagResponse"
            }
          },
          "categories": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/CategoryResponse"
            }
          },
          "coupons": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/CouponResponse"
            }
          }
        }
      },
      "ProductShippingResponse": {
        "type": "object",
        "properties": {
          "id": {
            "type": "integer",
            "format": "int32"
          },
          "name": {
            "type": "string"
          },
          "sku": {
            "type": "string"
          },
          "regular_price": {
            "type": "number",
            "format": "float"
          },
          "discount_price": {
            "type": "number",
            "format": "float"
          },
          "quantity": {
            "type": "integer",
            "format": "int32"
          },
          "description": {
            "type": "string"
          },
          "weight": {
            "type": "number",
            "format": "float"
          },
          "note": {
            "type": "string"
          },
          "published": {
            "type": "boolean"
          },
          "seller_id": {
            "type": "integer",
            "format": "int32"
          },
          "created_at": {
            "type": "string",
            "format": "date-time"
          },
          "updated_at": {
            "type": "string",
            "format": "date-time"
          },
          "shippings": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/ShippingResponse"
            }
          }
        }
      },
      "UserAddressResponse": {
        "type": "object",
        "properties": {
          "id": {
            "type": "integer",
            "format": "int32"
          },
          "first_name": {
            "type": "string"
          },
          "last_name": {
            "type": "string"
          },
          "email": {
            "type": "string",
            "pattern": "^[A-Z0-9._%-]+@[A-Z0-9.-]+.[A-Z]{2,4}$"
          },
          "phone_code": {
            "type": "string",
            "pattern": "^[0-9]{1,3}$"
          },
          "phone_number": {
            "type": "string",
            "pattern": "^[0-9]{4,12}$"
          },
          "created_at": {
            "type": "string",
            "format": "date-time"
          },
          "updated_at": {
            "type": "string",
            "format": "date-time"
          },
          "addresses": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/AddressResponse"
            }
          }
        }
      },
      "UserAddressProductResponse": {
        "type": "object",
        "properties": {
          "id": {
            "type": "integer",
            "format": "int32"
          },
          "first_name": {
            "type": "string"
          },
          "last_name": {
            "type": "string"
          },
          "email": {
            "type": "string",
            "pattern": "^[A-Z0-9._%-]+@[A-Z0-9.-]+.[A-Z]{2,4}$"
          },
          "phone_code": {
            "type": "string",
            "pattern": "^[0-9]{1,3}$"
          },
          "phone_number": {
            "type": "string",
            "pattern": "^[0-9]{4,12}$"
          },
          "created_at": {
            "type": "string",
            "format": "date-time"
          },
          "updated_at": {
            "type": "string",
            "format": "date-time"
          },
          "addresses": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/AddressResponse"
            }
          },
          "products": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/ProductResponse"
            }
          }
        }
      },
      "UserAddressProductShippingResponse": {
        "type": "object",
        "properties": {
          "id": {
            "type": "integer",
            "format": "int32"
          },
          "first_name": {
            "type": "string"
          },
          "last_name": {
            "type": "string"
          },
          "email": {
            "type": "string",
            "pattern": "^[A-Z0-9._%-]+@[A-Z0-9.-]+.[A-Z]{2,4}$"
          },
          "phone_code": {
            "type": "string",
            "pattern": "^[0-9]{1,3}$"
          },
          "phone_number": {
            "type": "string",
            "pattern": "^[0-9]{4,12}$"
          },
          "created_at": {
            "type": "string",
            "format": "date-time"
          },
          "updated_at": {
            "type": "string",
            "format": "date-time"
          },
          "addresses": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/AddressResponse"
            }
          },
          "products": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/ProductShippingResponse"
            }
          }
        }
      },
      "ErrResponse": {
        "type": "object",
        "properties": {
          "statusCode": {
            "type": "integer"
          },
          "message": {
            "type": "string"
          }
        }
      }
    },
    "examples": {
      "CorrectProductCreatePayload": {
        "description": "Create a new product with correct input data",
        "value": {
          "name": "Sepatu Sketcher Hiking",
          "sku": "xxx333yyy",
          "regular_price": 80000,
          "discount_price": 80000,
          "quantity": 1000,
          "description": "Sepatu Outdoor",
          "weight": 1000,
          "note": "Hiking",
          "published": true
        }
      },
      "IncorrectProductCreatePayload": {
        "description": "Create a new product with incorrect input data",
        "value": {
          "name": "Se",
          "sku": "xx",
          "regular_price": -80000,
          "discount_price": -80000,
          "quantity": -1000,
          "description": "Se",
          "weight": -1000,
          "note": "Hi",
          "published": "Yes publish"
        }
      },
      "CorrectProductTagCategoryCreatePayload": {
        "description": "Create a new product with its tags and category with correct input data",
        "value": {
          "name": "Sepatu Sketcher Hiking",
          "sku": "xxx333yyy",
          "regular_price": 80000,
          "discount_price": 80000,
          "quantity": 1000,
          "description": "Sepatu Outdoor",
          "weight": 1000,
          "note": "Hiking",
          "published": true,
          "tags": [
            "tag1",
            "tag2"
          ],
          "category": {
            "name": "Sepatu",
            "description": "Deskripsi sepatu"
          }
        }
      },
      "IncorrectProductTagCategoryCreatePayload": {
        "description": "Create a new product with its tags and category with incorrect input data",
        "value": {
          "name": "Se",
          "sku": "xx",
          "regular_price": -80000,
          "discount_price": -80000,
          "quantity": -1000,
          "description": "Se",
          "weight": -1000,
          "note": "Hi",
          "published": "Yes publish",
          "tags": [
            "ta",
            "ta"
          ],
          "category": {
            "name": "Se",
            "description": "De"
          }
        }
      },
      "CorrectProductTagCategoryCouponCreatePayload": {
        "description": "Create a new product with its tags, categories, and coupons with correct input data",
        "value": {
          "name": "Sepatu Sketcher Hiking",
          "sku": "xxx333yyy",
          "regular_price": 80000,
          "discount_price": 80000,
          "quantity": 1000,
          "description": "Sepatu Outdoor",
          "weight": 1000,
          "note": "Hiking",
          "published": true,
          "tags": [
            "tag1",
            "tag2"
          ],
          "categories": [
            {
              "name": "Sepatu 1",
              "description": "Deskripsi sepatu"
            },
            {
              "name": "Sepatu 2",
              "description": "Deskripsi sepatu"
            }
          ],
          "coupons": [
            {
              "code": "HUT RI",
              "description": "HUT RI",
              "discount_value": 25,
              "discount_type": "Potongan",
              "times_used": 10,
              "max_usage": 10,
              "start_date": "2023-08-17",
              "end_date": "2023-08-19"
            }
          ]
        }
      },
      "IncorrectProductTagCategoryCouponCreatePayload": {
        "description": "Create a new product with its tags, categories, and coupons with incorrect input data",
        "value": {
          "name": "Se",
          "sku": "xx",
          "regular_price": -80000,
          "discount_price": -80000,
          "quantity": -1000,
          "description": "Se",
          "weight": -1000,
          "note": "Hi",
          "published": "Yes publish",
          "tags": [
            "ta",
            "ta"
          ],
          "categories": [
            {
              "name": "Se",
              "description": "De"
            },
            {
              "name": "Se",
              "description": "De"
            }
          ],
          "coupons": [
            {
              "code": "HU",
              "description": "HU",
              "discount_value": 2500,
              "discount_type": "Po",
              "times_used": -10,
              "max_usage": -10,
              "start_date": "Tanggal Awal",
              "end_date": "Tanggal Akhir"
            }
          ]
        }
      },
      "CorrectUserCreatePayload": {
        "description": "Create a new user",
        "value": {
          "first_name": "Bung",
          "last_name": "Danar",
          "email": "danar@gmail.com",
          "phone_code": "62",
          "phone_number": "85279116866"
        }
      },
      "IncorrectUserCreatePayload": {
        "description": "Create a new user with incorrect input data",
        "value": {
          "first_name": "Bu",
          "last_name": "Da",
          "email": "danar",
          "phone_code": "62a",
          "phone_number": "8527911686677777"
        }
      },
      "CorrectUserAddressCreatePayload": {
        "description": "Create a new user with its address",
        "value": {
          "first_name": "Bung",
          "last_name": "Danar",
          "email": "danar@gmail.com",
          "phone_code": "62",
          "phone_number": "85279116866",
          "address": {
            "street": "Kapuk",
            "city": "Jakarta",
            "country": "Indo",
            "postal_code": "34162"
          }
        }
      },
      "IncorrectUserAddressCreatePayload": {
        "description": "Create a new user with its address with incorrect input data",
        "value": {
          "first_name": "Bu",
          "last_name": "Da",
          "email": "danar",
          "phone_code": "62a",
          "phone_number": "8527911686677777",
          "address": {
            "street": "Ka",
            "city": "Ja",
            "country": "In",
            "postal_code": "3416200000"
          }
        }
      },
      "CorrectUserAddressProductCreatePayload": {
        "description": "Create a new user with its addresses and product",
        "value": {
          "first_name": "Bung",
          "last_name": "Danar",
          "email": "danar@gmail.com",
          "phone_code": "62",
          "phone_number": "85279116866",
          "addresses": [
            {
              "street": "Kapuk",
              "city": "Jakarta",
              "country": "Indo",
              "postal_code": "34162"
            },
            {
              "street": "Harpmul",
              "city": "Jakarta",
              "country": "Indo",
              "postal_code": "34001"
            }
          ],
          "product": {
            "description": "Sepatu Outdoor",
            "discount_price": 80000,
            "name": "Sepatu Sketcher Hiking",
            "note": "Hiking",
            "quantity": 1000,
            "regular_price": 80000,
            "sku": "xxx333yyy",
            "weight": 1.25,
            "published": true
          }
        }
      },
      "IncorrectUserAddressProductCreatePayload": {
        "description": "Create a new user with its addresses and product with incorrect input data",
        "value": {
          "first_name": "Bu",
          "last_name": "Da",
          "email": "danar",
          "phone_code": "62a",
          "phone_number": "8527911686677777",
          "addresses": [
            {
              "street": "Ka",
              "city": "Ja",
              "country": "In",
              "postal_code": "3416200000"
            },
            {
              "street": "Ha",
              "city": "Ja",
              "country": "In",
              "postal_code": "abcde"
            }
          ],
          "product": {
            "description": "Se",
            "discount_price": -80000,
            "name": "Se",
            "note": "Hi",
            "quantity": 10000,
            "regular_price": -80000,
            "sku": "xxx333yyy",
            "weight": 1.25,
            "published": true
          }
        }
      },
      "CorrectUserAddressProductShippingCreatePayload": {
        "description": "Create a new user with its addresses and product (with its shipping)",
        "value": {
          "first_name": "Bung",
          "last_name": "Danar",
          "email": "danar@gmail.com",
          "phone_code": "62",
          "phone_number": "85279116866",
          "addresses": [
            {
              "street": "Kapuk",
              "city": "Jakarta",
              "country": "Indo",
              "postal_code": "34162"
            },
            {
              "street": "Harpmul",
              "city": "Jakarta",
              "country": "Indo",
              "postal_code": "34001"
            }
          ],
          "product": {
            "description": "Sepatu Outdoor",
            "discount_price": 80000,
            "name": "Sepatu Sketcher Hiking",
            "note": "Hiking",
            "quantity": 1000,
            "regular_price": 80000,
            "sku": "xxx333yyy",
            "weight": 1.25,
            "published": true
          },
          "shipping": {
            "description": "Pengiriman instan",
            "charge": 50000,
            "free": false,
            "estimated_days": 8
          }
        }
      },
      "IncorrectUserAddressProductShippingCreatePayload": {
        "description": "Create a new user with its addresses and product (with its shipping) with incorrect input data",
        "value": {
          "first_name": "Bu",
          "last_name": "Da",
          "email": "danar",
          "phone_code": "62a",
          "phone_number": "8527911686677777",
          "addresses": [
            {
              "street": "Ka",
              "city": "Ja",
              "country": "In",
              "postal_code": "3416200000"
            },
            {
              "street": "Ha",
              "city": "Ja",
              "country": "In",
              "postal_code": "abcde"
            }
          ],
          "product": {
            "description": "Se",
            "discount_price": -80000,
            "name": "Se",
            "note": "Hi",
            "quantity": 10000,
            "regular_price": -80000,
            "sku": "xxx333yyy",
            "weight": 1.25,
            "published": true
          },
          "shipping": {
            "description": "Pe",
            "charge": -50000,
            "free": "It is free",
            "estimated_days": 80
          }
        }
      }
    }
  }
}