{
  "openapi": "3.0.3",
  "info": {
    "title": "RESTful API for Fuzzing",
    "version": "1.0",
    "description": "OpenAPI spec for Experimental RESTful API for Fuzzing",
    "contact": {
      "name": "Danar Gumilang Putera",
      "email": "danar.g.putera@gmail.com",
      "url": "https://github.com/bungdanar"
    },
    "license": {
      "name": "MIT",
      "url": "https://opensource.org/license/mit/"
    }
  },
  "servers": [
    {
      "url": "http://localhost:5000/api",
      "description": "Experimental RESTful API Server for Fuzzing"
    }
  ],
  "externalDocs": {
    "url": "https://github.com/bungdanar",
    "description": "Experimental RESTful API Server Written in NodeJs and Python"
  },
  "paths": {
    "/product": {
      "post": {
        "tags": [
          "Product"
        ],
        "summary": "Create a new product",
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/ProductCreatePayload"
              },
              "examples": {
                "CorrectProductCreatePayload": {
                  "$ref": "#/components/examples/CorrectProductCreatePayload"
                },
                "IncorrectProductCreatePayload": {
                  "$ref": "#/components/examples/IncorrectProductCreatePayload"
                }
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Successfully create new product",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ProductResponse"
                }
              }
            }
          },
          "400": {
            "description": "Bad request error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrResponse"
                }
              }
            }
          },
          "500": {
            "description": "Internal server error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrResponse"
                }
              }
            }
          }
        }
      }
    },
    "/product-tag-category": {
      "post": {
        "tags": [
          "Product Tags Category"
        ],
        "summary": "Create a new product with its tags and category",
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/ProductTagCategoryCreatePayload"
              },
              "examples": {
                "CorrectProductTagCategoryCreatePayload": {
                  "$ref": "#/components/examples/CorrectProductTagCategoryCreatePayload"
                },
                "IncorrectProductTagCategoryCreatePayload": {
                  "$ref": "#/components/examples/IncorrectProductTagCategoryCreatePayload"
                }
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Successfully create a new product with its tags and category",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ProductTagCategoryResponse"
                }
              }
            }
          },
          "400": {
            "description": "Bad request error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrResponse"
                }
              }
            }
          },
          "500": {
            "description": "Internal server error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrResponse"
                }
              }
            }
          }
        }
      }
    },
    "/product-tag-category-coupon": {
      "post": {
        "tags": [
          "Product Tags Categories Coupons"
        ],
        "summary": "Create a new product with its tags, categories, and coupons",
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/ProductTagCategoryCouponCreatePayload"
              },
              "examples": {
                "CorrectProductTagCategoryCouponCreatePayload": {
                  "$ref": "#/components/examples/CorrectProductTagCategoryCouponCreatePayload"
                },
                "IncorrectProductTagCategoryCouponCreatePayload": {
                  "$ref": "#/components/examples/IncorrectProductTagCategoryCouponCreatePayload"
                }
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Successfully create a new product with its tags, categories, and coupons",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ProductTagCategoryCouponResponse"
                }
              }
            }
          },
          "400": {
            "description": "Bad request error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrResponse"
                }
              }
            }
          },
          "500": {
            "description": "Internal server error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrResponse"
                }
              }
            }
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "ProductCreatePayload": {
        "type": "object",
        "required": [
          "name",
          "sku",
          "regular_price",
          "discount_price",
          "quantity",
          "description",
          "weight",
          "note"
        ],
        "properties": {
          "name": {
            "type": "string",
            "minLength": 3,
            "maxLength": 255
          },
          "sku": {
            "type": "string",
            "minLength": 3,
            "maxLength": 255
          },
          "regular_price": {
            "type": "number",
            "format": "float",
            "minimum": 0
          },
          "discount_price": {
            "type": "number",
            "format": "float",
            "minimum": 0,
            "description": "Must be less than or equal to regular_price"
          },
          "quantity": {
            "type": "integer",
            "format": "int32",
            "minimum": 0,
            "maximum": 9999
          },
          "description": {
            "type": "string",
            "minLength": 3,
            "maxLength": 1000
          },
          "weight": {
            "type": "number",
            "format": "float",
            "minimum": 0,
            "maximum": 1000
          },
          "note": {
            "type": "string",
            "minLength": 3,
            "maxLength": 255
          },
          "published": {
            "type": "boolean",
            "default": false
          }
        }
      },
      "TagsCreatePayload": {
        "type": "array",
        "items": {
          "type": "string",
          "minLength": 3,
          "maxLength": 255
        }
      },
      "CategoryCreatePayload": {
        "type": "object",
        "required": [
          "name",
          "description"
        ],
        "properties": {
          "name": {
            "type": "string",
            "minLength": 3,
            "maxLength": 255
          },
          "description": {
            "type": "string",
            "minLength": 3,
            "maxLength": 1000
          }
        }
      },
      "CouponCreatePayload": {
        "type": "object",
        "required": [
          "code",
          "description",
          "discount_value",
          "discount_type",
          "max_usage",
          "start_date",
          "end_date"
        ],
        "properties": {
          "code": {
            "type": "string",
            "minLength": 3,
            "maxLength": 255
          },
          "description": {
            "type": "string",
            "minLength": 3,
            "maxLength": 1000
          },
          "discount_value": {
            "type": "number",
            "format": "float",
            "minimum": 0,
            "maximum": 100
          },
          "discount_type": {
            "type": "string",
            "minLength": 3,
            "maxLength": 255
          },
          "times_used": {
            "type": "integer",
            "format": "int32",
            "minimum": 0,
            "default": 0,
            "description": "Must be less than or equal to max_usage"
          },
          "max_usage": {
            "type": "integer",
            "format": "int32",
            "minimum": 0
          },
          "start_date": {
            "type": "string",
            "format": "date-time"
          },
          "end_date": {
            "type": "string",
            "format": "date-time",
            "description": "Must be greater than or equal to start_date"
          }
        }
      },
      "ProductTagCategoryCreatePayload": {
        "type": "object",
        "required": [
          "tags",
          "category"
        ],
        "allOf": [
          {
            "$ref": "#/components/schemas/ProductCreatePayload"
          }
        ],
        "properties": {
          "tags": {
            "$ref": "#/components/schemas/TagsCreatePayload"
          },
          "category": {
            "$ref": "#/components/schemas/CategoryCreatePayload"
          }
        }
      },
      "ProductTagCategoryCouponCreatePayload": {
        "type": "object",
        "required": [
          "tags",
          "categories",
          "coupons"
        ],
        "allOf": [
          {
            "$ref": "#/components/schemas/ProductCreatePayload"
          }
        ],
        "properties": {
          "tags": {
            "$ref": "#/components/schemas/TagsCreatePayload"
          },
          "categories": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/CategoryCreatePayload"
            }
          },
          "coupons": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/CouponCreatePayload"
            }
          }
        }
      },
      "TagResponse": {
        "type": "object",
        "properties": {
          "id": {
            "type": "integer",
            "format": "int32"
          },
          "name": {
            "type": "string"
          },
          "created_at": {
            "type": "string",
            "format": "date-time"
          },
          "updated_at": {
            "type": "string",
            "format": "date-time"
          }
        }
      },
      "CategoryResponse": {
        "type": "object",
        "properties": {
          "id": {
            "type": "integer",
            "format": "int32"
          },
          "name": {
            "type": "string"
          },
          "description": {
            "type": "string"
          },
          "active": {
            "type": "boolean"
          },
          "created_at": {
            "type": "string",
            "format": "date-time"
          },
          "updated_at": {
            "type": "string",
            "format": "date-time"
          }
        }
      },
      "CouponResponse": {
        "type": "object",
        "properties": {
          "id": {
            "type": "integer",
            "format": "int32"
          },
          "code": {
            "type": "string"
          },
          "description": {
            "type": "string"
          },
          "discount_value": {
            "type": "number",
            "format": "float"
          },
          "discount_type": {
            "type": "string"
          },
          "times_used": {
            "type": "integer",
            "format": "int32"
          },
          "max_usage": {
            "type": "integer",
            "format": "int32"
          },
          "start_date": {
            "type": "string",
            "format": "date-time"
          },
          "end_date": {
            "type": "string",
            "format": "date-time"
          },
          "created_at": {
            "type": "string",
            "format": "date-time"
          },
          "updated_at": {
            "type": "string",
            "format": "date-time"
          }
        }
      },
      "ProductResponse": {
        "type": "object",
        "properties": {
          "id": {
            "type": "integer",
            "format": "int32"
          },
          "name": {
            "type": "string"
          },
          "sku": {
            "type": "string"
          },
          "regular_price": {
            "type": "number",
            "format": "float"
          },
          "discount_price": {
            "type": "number",
            "format": "float"
          },
          "quantity": {
            "type": "integer",
            "format": "int32"
          },
          "description": {
            "type": "string"
          },
          "weight": {
            "type": "number",
            "format": "float"
          },
          "note": {
            "type": "string"
          },
          "published": {
            "type": "boolean"
          },
          "created_at": {
            "type": "string",
            "format": "date-time"
          },
          "updated_at": {
            "type": "string",
            "format": "date-time"
          }
        }
      },
      "ProductTagCategoryResponse": {
        "type": "object",
        "allOf": [
          {
            "$ref": "#/components/schemas/ProductResponse"
          }
        ],
        "properties": {
          "tags": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/TagResponse"
            }
          },
          "categories": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/CategoryResponse"
            }
          }
        }
      },
      "ProductTagCategoryCouponResponse": {
        "type": "object",
        "allOf": [
          {
            "$ref": "#/components/schemas/ProductTagCategoryResponse"
          }
        ],
        "properties": {
          "coupons": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/CouponResponse"
            }
          }
        }
      },
      "ErrResponse": {
        "type": "object",
        "properties": {
          "statusCode": {
            "type": "integer"
          },
          "message": {
            "type": "string"
          }
        }
      }
    },
    "examples": {
      "CorrectProductCreatePayload": {
        "description": "Create a new product with correct input data",
        "value": {
          "name": "Sepatu Sketcher Hiking",
          "sku": "xxx333yyy",
          "regular_price": 80000,
          "discount_price": 80000,
          "quantity": 1000,
          "description": "Sepatu Outdoor",
          "weight": 1000,
          "note": "Hiking",
          "published": true
        }
      },
      "IncorrectProductCreatePayload": {
        "description": "Create a new product with incorrect input data",
        "value": {
          "name": "Se",
          "sku": "xx",
          "regular_price": -80000,
          "discount_price": -80000,
          "quantity": -1000,
          "description": "Se",
          "weight": -1000,
          "note": "Hi",
          "published": "Yes publish"
        }
      },
      "CorrectProductTagCategoryCreatePayload": {
        "description": "Create a new product with its tags and category with correct input data",
        "value": {
          "name": "Sepatu Sketcher Hiking",
          "sku": "xxx333yyy",
          "regular_price": 80000,
          "discount_price": 80000,
          "quantity": 1000,
          "description": "Sepatu Outdoor",
          "weight": 1000,
          "note": "Hiking",
          "published": true,
          "tags": [
            "tag1",
            "tag2"
          ],
          "category": {
            "name": "Sepatu",
            "description": "Deskripsi sepatu"
          }
        }
      },
      "IncorrectProductTagCategoryCreatePayload": {
        "description": "Create a new product with its tags and category with incorrect input data",
        "value": {
          "name": "Se",
          "sku": "xx",
          "regular_price": -80000,
          "discount_price": -80000,
          "quantity": -1000,
          "description": "Se",
          "weight": -1000,
          "note": "Hi",
          "published": "Yes publish",
          "tags": [
            "ta",
            "ta"
          ],
          "category": {
            "name": "Se",
            "description": "De"
          }
        }
      },
      "CorrectProductTagCategoryCouponCreatePayload": {
        "description": "Create a new product with its tags, categories, and coupons with correct input data",
        "value": {
          "name": "Sepatu Sketcher Hiking",
          "sku": "xxx333yyy",
          "regular_price": 80000,
          "discount_price": 80000,
          "quantity": 1000,
          "description": "Sepatu Outdoor",
          "weight": 1000,
          "note": "Hiking",
          "published": true,
          "tags": [
            "tag1",
            "tag2"
          ],
          "categories": [
            {
              "name": "Sepatu 1",
              "description": "Deskripsi sepatu"
            },
            {
              "name": "Sepatu 2",
              "description": "Deskripsi sepatu"
            }
          ],
          "coupons": [
            {
              "code": "HUT RI",
              "description": "HUT RI",
              "discount_value": 25,
              "discount_type": "Potongan",
              "times_used": 10,
              "max_usage": 10,
              "start_date": "2023-08-17",
              "end_date": "2023-08-19"
            }
          ]
        }
      },
      "IncorrectProductTagCategoryCouponCreatePayload": {
        "description": "Create a new product with its tags, categories, and coupons with incorrect input data",
        "value": {
          "name": "Se",
          "sku": "xx",
          "regular_price": -80000,
          "discount_price": -80000,
          "quantity": -1000,
          "description": "Se",
          "weight": -1000,
          "note": "Hi",
          "published": "Yes publish",
          "tags": [
            "ta",
            "ta"
          ],
          "categories": [
            {
              "name": "Se",
              "description": "De"
            },
            {
              "name": "Se",
              "description": "De"
            }
          ],
          "coupons": [
            {
              "code": "HU",
              "description": "HU",
              "discount_value": 2500,
              "discount_type": "Po",
              "times_used": -10,
              "max_usage": -10,
              "start_date": "Tanggal Awal",
              "end_date": "Tanggal Akhir"
            }
          ]
        }
      }
    }
  }
}